services: # Описание микросервисов (контейнеров)
  pl-ui: # Имя контейнера (по умолчанию добавится -1)
    image: pl-ui:v1 # Базовый образ для контейнера (если такого нет, соберется из докерфайла)
    build: # Инструкции для сборки образа, если он не найден
      context: . # Контекст сборки (текущая директория)
      dockerfile: Dockerfile-chromium # Имя Dockerfile на основе которого будет сборка
      shm_size: 2gb
    volumes: # Тома для монтирования
      - ./:/usr/workspace
      - /dev/shm:/dev/shm
    command: /bin/sh -c "STAGE=$$STAGE BROWSER=$$BROWSER pytest -sv -o log_cli=true -m=$$SUITE -n=$$THREADS --alluredir=allure-results"
    environment: # Переменные окружения
      STAGE: ${STAGE:-staging}
      BROWSER: ${BROWSER:-chrome}
      SUITE: ${SUITE}
      THREADS: ${THREADS:-1}
    tty: true # Для цветного вывода логов

#    комманда для запуска $env:SUITE = "login"; docker-compose up